/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const DEFAULT_WIDTH: number
export const DEFAULT_HEIGHT: number
export const DEFAULT_FPS: number
export interface Resolution {
  height: number
  width: number
}
export const enum Colorspace {
  I420 = 2,
  YV12 = 3,
  NV12 = 4,
  NV21 = 5,
  I422 = 6,
  YV16 = 7,
  NV16 = 8,
  YUYV = 9,
  UYVY = 10,
  V210 = 11,
  I444 = 12,
  YV24 = 13,
  BGR = 14,
  BGRA = 15,
  RGB = 16,
}
export const enum VideoEncoding {
  AV1 = 1,
  H264 = 2,
}
export declare function convertImagesToVideo(config: Config): Array<number>
export declare class Config {
  images: Array<string>
  fps?: number
  height?: number
  width?: number
  colorspace?: Colorspace
  outputPath?: string
  fpi?: number
  videoEncoding?: VideoEncoding
  constructor()
  static createConfig(
    images: Array<string>,
    fps?: number | undefined | null,
    height?: number | undefined | null,
    width?: number | undefined | null,
    colorspace?: Colorspace | undefined | null,
    outputPath?: string | undefined | null,
    fpi?: number | undefined | null,
    videoEncoding?: VideoEncoding | undefined | null,
  ): Config
  static defaultConfigWithImages(images: Array<string>): Config
  set addImages(images: Array<string>)
  set addImage(image: string)
  set fps(fps: number)
  set outputPath(outputPath: string)
  set colorspace(cs: Colorspace)
  set resolustion(width: number, height: number)
  set fpi(fpi: number)
  set videoEncoding(videoEncoding: VideoEncoding)
}
